site_name: Vitrua.top
site_url: https://docs.vitrua.top/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.prune
    - navigation.footer
  custom_dir: overrides


  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep-orange
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    logo: logo
  font:
    text: DM Sans

plugins:
  - social
  - search
  - ultralytics:
      verbose: True
      enabled: True
      default_image: "https://github.com/Vitrua/website/blob/main/docs/hero.png"
      add_desc: True
      add_image: True
      add_keywords: True
      add_share_buttons: True
      add_authors: False
      add_json_ld: False
      add_css: True
  - git-revision-date-localized:
      type: date
#  - search.highlight
#  - search.share
extra:
  social:
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/Vitrua
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/vitruastudio
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/phuongcth
#  analytics: 
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            Thanks for your feedback!
#        - icon: material/emoticon-sad-outline
#          name: This page could be improved
#          data: 0
#          note: >- 
#            Thanks for your feedback! Help us improve this page by
#            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: |
  &copy; 2024 <a href="https://vitrua.top"  target="_blank" rel="noopener">Vitrua</a>
